import { useEffect, useMemo, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useAuth } from "../../../../../hooks/useAuth";
import { useInfo } from "../../../../../hooks/useInfo";
import { FieldWrapper } from "../../../../../components/Form/fields/FieldWrapper";
import { getInputClassName } from "../../../../../components/Form/fields/inputStyles";
import PersonnelService from "../../../../../services/personnel.service";
import PresencePersonnelService from "../../../../../services/presencePersonnel.service";

const schema = z.object({ personnel_id: z.string().min(1), date: z.string().min(1), statut: z.string().min(1), note: z.string().optional() });
type FormValues = z.infer<typeof schema>;
function getErrorMessage(error: unknown) { if (typeof error === "object" && error !== null && "response" in error && typeof error.response === "object" && error.response !== null && "data" in error.response && typeof error.response.data === "object" && error.response.data !== null && "message" in error.response.data && typeof error.response.data.message === "string") return error.response.data.message; return "La presence personnel n'a pas pu etre enregistree."; }
export default function PresencePersonnelForm() { const { etablissement_id } = useAuth(); const { info } = useInfo(); const service = useMemo(() => new PresencePersonnelService(), []); const [personnels, setPersonnels] = useState<any[]>([]); useEffect(() => { const load = async () => { if (!etablissement_id) return; const personnelService = new PersonnelService(); const result = await personnelService.getAll({ take: 500, where: JSON.stringify({ etablissement_id }), includeSpec: JSON.stringify({ utilisateur: { include: { profil: true } } }) }); setPersonnels(result?.status.success ? result.data.data : []); }; void load(); }, [etablissement_id]); const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { personnel_id: "", date: new Date().toISOString().slice(0,10), statut: "PRESENT", note: "" } }); const onSubmit = async (data: FormValues) => { try { await service.create({ personnel_id: data.personnel_id, date: new Date(data.date), statut: data.statut, note: data.note || null }); info("Presence personnel creee avec succes !", "success"); form.reset({ ...form.getValues(), personnel_id: "", note: "" }); } catch (error) { info(getErrorMessage(error), "error"); } }; return <form onSubmit={form.handleSubmit(onSubmit)} className="grid gap-5 md:grid-cols-2"><Controller control={form.control} name="personnel_id" render={({ field, fieldState }) => <FieldWrapper id="personnel_id" label="Personnel" required error={fieldState.error?.message}><select {...field} className={getInputClassName(Boolean(fieldState.error))}><option value="">Selectionner un personnel</option>{personnels.map((item) => <option key={item.id} value={item.id}>{item.code_personnel ?? item.id}</option>)}</select></FieldWrapper>} /><Controller control={form.control} name="date" render={({ field, fieldState }) => <FieldWrapper id="date" label="Date" required error={fieldState.error?.message}><input type="date" {...field} className={getInputClassName(Boolean(fieldState.error))} /></FieldWrapper>} /><Controller control={form.control} name="statut" render={({ field, fieldState }) => <FieldWrapper id="statut" label="Statut" required error={fieldState.error?.message}><select {...field} className={getInputClassName(Boolean(fieldState.error))}><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="RETARD">Retard</option><option value="CONGE">Conge</option></select></FieldWrapper>} /><Controller control={form.control} name="note" render={({ field, fieldState }) => <FieldWrapper id="note" label="Note" error={fieldState.error?.message}><textarea {...field} className={getInputClassName(Boolean(fieldState.error))} /></FieldWrapper>} /><div className="md:col-span-2 flex justify-end"><button type="submit" className="inline-flex items-center gap-2 rounded-2xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Enregistrer</button></div></form>; }
