// This file was auto-generated by prisma-generator-typescript-interfaces

/**
 * *
 *  * =========================
 *  * ENUMS (simples)
 *  * =========================
 */
export type StatutCompte = "ACTIF" | "INACTIF" | "SUSPENDU";

export type StatutInscription = "INSCRIT" | "TRANSFERE" | "SORTI";

export type StatutPresence = "PRESENT" | "ABSENT" | "RETARD" | "EXCUSE";

export type StatutFacture = "BROUILLON" | "EMISE" | "PARTIELLE" | "PAYEE" | "ANNULEE" | "EN_RETARD";

export type TypeCanal = "EMAIL" | "SMS" | "APP";

export type TypeEvaluation = "DEVOIR" | "EXAMEN" | "ORAL" | "AUTRE";

/**
 * *
 *  * =========================
 *  * 1) NOYAU
 *  * =========================
 */
export interface Etablissement {
  id: string;
  nom: string;
  code: string | null;
  fuseau_horaire: string | null;
  parametres_json: JsonValue | null;
  created_at: Date;
  updated_at: Date;
  sites?: Site[];
  annees?: AnneeScolaire[];
  etablissementReferenciel?: EtablissementReferenciel[];
  utilisateurs?: Utilisateur[];
  roles?: Role[];
  permissions?: Permission[];
  eleves?: Eleve[];
  personnel?: Personnel[];
  departements?: Departement[];
  matieres?: Matiere[];
  canaux?: CanalCommunication[];
  catalogueFrais?: CatalogueFrais[];
  remises?: Remise[];
  fichiers?: Fichier[];
  journauxAudit?: JournalAudit[];
  webhooks?: Webhook[];
  jetons?: JetonIntegration[];
  ParentTuteur?: ParentTuteur[];
  NiveauScolaire?: NiveauScolaire[];
  Classe?: Classe[];
  Programme?: Programme[];
  Cours?: Cours[];
  RegleNote?: RegleNote[];
  EvenementCalendrier?: EvenementCalendrier[];
  Annonce?: Annonce[];
  Message?: Message[];
  Facture?: Facture[];
}

export interface Site {
  id: string;
  etablissement_id: string;
  nom: string;
  adresse: string | null;
  telephone: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  salles?: Salle[];
  classes?: Classe[];
  evenements?: EvenementCalendrier[];
}

export interface AnneeScolaire {
  id: string;
  etablissement_id: string;
  nom: string;
  date_debut: Date;
  date_fin: Date;
  est_active: boolean;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  periodes?: Periode[];
  classes?: Classe[];
  inscriptions?: Inscription[];
  programmes?: Programme[];
  cours?: Cours[];
  factures?: Facture[];
  plansPaiement?: PlanPaiementEleve[];
  abonnementsTransport?: AbonnementTransport[];
  abonnementsCantine?: AbonnementCantine[];
}

export interface Periode {
  id: string;
  annee_scolaire_id: string;
  nom: string;
  date_debut: Date;
  date_fin: Date;
  ordre: number | null;
  created_at: Date;
  updated_at: Date;
  annee?: AnneeScolaire;
  evaluations?: Evaluation[];
  bulletins?: Bulletin[];
}

export interface Salle {
  id: string;
  site_id: string;
  nom: string;
  capacite: number | null;
  type: string | null;
  created_at: Date;
  updated_at: Date;
  site?: Site;
  emploiDuTemps?: EmploiDuTemps[];
}

export interface Referenciel {
  id: string;
  titre: string;
  code: string;
  etablissementReferenciel?: EtablissementReferenciel[];
}

export interface EtablissementReferenciel {
  id: string;
  referenciel_id: string;
  etablissement_id: string;
  valeur: string;
  etablissement?: Etablissement;
  Referenciel?: Referenciel | null;
  referencielId: string | null;
}

/**
 * *
 *  * =========================
 *  * 2) COMPTES & DROITS
 *  * =========================
 */
export interface Utilisateur {
  id: string;
  etablissement_id: string | null;
  email: string | null;
  telephone: string | null;
  mot_de_passe_hash: string | null;
  statut: StatutCompte;
  dernier_login: Date | null;
  scope_json: JsonValue | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement | null;
  profil?: Profil | null;
  roles?: UtilisateurRole[];
  messagesEnvoyes?: Message[];
  notifications?: Notification[];
  fichiers?: Fichier[];
  journauxAudit?: JournalAudit[];
  Eleve?: Eleve[];
  ParentTuteur?: ParentTuteur[];
  Personnel?: Personnel[];
  MessageDestinataire?: MessageDestinataire[];
}

export interface Profil {
  id: string;
  utilisateur_id: string;
  prenom: string;
  nom: string;
  date_naissance: Date | null;
  genre: string | null;
  photo_url: string | null;
  adresse: string | null;
  contact_urgence_json: JsonValue | null;
  created_at: Date;
  updated_at: Date;
  utilisateur?: Utilisateur;
}

export interface Role {
  id: string;
  etablissement_id: string | null;
  nom: string;
  created_at: Date;
  updated_at: Date;
  scope_json: JsonValue | null;
  etablissement?: Etablissement | null;
  permissions?: RolePermission[];
  utilisateurs?: UtilisateurRole[];
}

export interface Permission {
  id: string;
  etablissement_id: string | null;
  code: string;
  description: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement | null;
  roles?: RolePermission[];
}

export interface RolePermission {
  role_id: string;
  permission_id: string;
  role?: Role;
  permission?: Permission;
}

export interface UtilisateurRole {
  utilisateur_id: string;
  role_id: string;
  scope_json: JsonValue | null;
  utilisateur?: Utilisateur;
  role?: Role;
}

/**
 * *
 *  * =========================
 *  * 3) SCOLARITÉ
 *  * =========================
 */
export interface Eleve {
  id: string;
  etablissement_id: string;
  code_eleve: string | null;
  utilisateur_id: string | null;
  statut: string | null;
  date_entree: Date | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  utilisateur?: Utilisateur | null;
  liensParents?: EleveParentTuteur[];
  inscriptions?: Inscription[];
  identifiants?: IdentifiantEleve[];
  notes?: Note[];
  presences?: PresenceEleve[];
  justificatifs?: JustificatifAbsence[];
  incidents?: IncidentDisciplinaire[];
  recompenses?: Recompense[];
  bulletins?: Bulletin[];
  factures?: Facture[];
  plansPaiement?: PlanPaiementEleve[];
  abonnementsTransport?: AbonnementTransport[];
  abonnementsCantine?: AbonnementCantine[];
  emprunts?: Emprunt[];
}

export interface ParentTuteur {
  id: string;
  etablissement_id: string;
  utilisateur_id: string | null;
  nom_complet: string;
  telephone: string | null;
  email: string | null;
  adresse: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  utilisateur?: Utilisateur | null;
  eleves?: EleveParentTuteur[];
}

export interface EleveParentTuteur {
  eleve_id: string;
  parent_tuteur_id: string;
  relation: string | null;
  est_principal: boolean;
  autorise_recuperation: boolean;
  eleve?: Eleve;
  parent_tuteur?: ParentTuteur;
}

export interface NiveauScolaire {
  id: string;
  etablissement_id: string;
  nom: string;
  ordre: number | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  classes?: Classe[];
  programmes?: Programme[];
}

export interface Classe {
  id: string;
  etablissement_id: string;
  annee_scolaire_id: string;
  niveau_scolaire_id: string;
  site_id: string | null;
  nom: string;
  enseignant_principal_id: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  annee?: AnneeScolaire;
  niveau?: NiveauScolaire;
  site?: Site | null;
  enseignant_principal?: Enseignant | null;
  inscriptions?: Inscription[];
  cours?: Cours[];
  sessionsAppel?: SessionAppel[];
  bulletins?: Bulletin[];
  emploiDuTemps?: EmploiDuTemps[];
}

export interface Inscription {
  id: string;
  eleve_id: string;
  classe_id: string;
  annee_scolaire_id: string;
  date_inscription: Date;
  statut: StatutInscription;
  date_sortie: Date | null;
  raison_sortie: string | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
  classe?: Classe;
  annee?: AnneeScolaire;
}

export interface IdentifiantEleve {
  id: string;
  eleve_id: string;
  type: string;
  valeur: string;
  delivre_le: Date | null;
  expire_le: Date | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
}

/**
 * *
 *  * =========================
 *  * 4) PERSONNEL
 *  * =========================
 */
export interface Personnel {
  id: string;
  etablissement_id: string;
  code_personnel: string | null;
  utilisateur_id: string | null;
  date_embauche: Date | null;
  statut: string | null;
  poste: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  utilisateur?: Utilisateur | null;
  enseignant?: Enseignant | null;
  presences?: PresencePersonnel | null;
  Emprunt?: Emprunt[];
}

export interface Enseignant {
  id: string;
  personnel_id: string;
  departement_principal_id: string | null;
  created_at: Date;
  updated_at: Date;
  personnel?: Personnel;
  departement?: Departement | null;
  cours?: Cours[];
  evaluationsCreees?: Evaluation[];
  sessionsAppel?: SessionAppel[];
  emploiDuTemps?: EmploiDuTemps[];
  classesPrincipales?: Classe[];
}

export interface Departement {
  id: string;
  etablissement_id: string;
  nom: string;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  matieres?: Matiere[];
  enseignants?: Enseignant[];
}

/**
 * *
 *  * =========================
 *  * 5) PÉDAGOGIE
 *  * =========================
 */
export interface Matiere {
  id: string;
  etablissement_id: string;
  code: string | null;
  nom: string;
  departement_id: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  departement?: Departement | null;
  cours?: Cours[];
  lignesProgramme?: ProgrammeMatiere[];
  lignesBulletin?: BulletinLigne[];
  EmploiDuTemps?: EmploiDuTemps[];
}

export interface Programme {
  id: string;
  etablissement_id: string;
  annee_scolaire_id: string;
  niveau_scolaire_id: string;
  nom: string;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  annee?: AnneeScolaire;
  niveau?: NiveauScolaire;
  matieres?: ProgrammeMatiere[];
}

export interface ProgrammeMatiere {
  id: string;
  programme_id: string;
  matiere_id: string;
  heures_semaine: number | null;
  coefficient: number | null;
  created_at: Date;
  updated_at: Date;
  programme?: Programme;
  matiere?: Matiere;
}

export interface Cours {
  id: string;
  etablissement_id: string;
  annee_scolaire_id: string;
  classe_id: string;
  matiere_id: string;
  enseignant_id: string;
  coefficient_override: number | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  annee?: AnneeScolaire;
  classe?: Classe;
  matiere?: Matiere;
  enseignant?: Enseignant;
  evaluations?: Evaluation[];
  emploiDuTemps?: EmploiDuTemps[];
}

export interface TypeEvaluationRef {
  id: string;
  etablissement_id: string;
  nom: string;
  poids_defaut: number | null;
  created_at: Date;
  updated_at: Date;
  evaluations?: Evaluation[];
}

export interface Evaluation {
  id: string;
  cours_id: string;
  periode_id: string;
  type_evaluation_id: string | null;
  type: TypeEvaluation;
  titre: string;
  date: Date;
  note_max: number;
  poids: number | null;
  est_publiee: boolean;
  cree_par_enseignant_id: string | null;
  created_at: Date;
  updated_at: Date;
  cours?: Cours;
  periode?: Periode;
  typeRef?: TypeEvaluationRef | null;
  createur?: Enseignant | null;
  notes?: Note[];
}

export interface Note {
  id: string;
  evaluation_id: string;
  eleve_id: string;
  score: number;
  commentaire: string | null;
  note_le: Date | null;
  note_par: string | null;
  created_at: Date;
  updated_at: Date;
  evaluation?: Evaluation;
  eleve?: Eleve;
}

export interface RegleNote {
  id: string;
  etablissement_id: string;
  scope: string | null;
  regle_json: JsonValue;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
}

export interface Bulletin {
  id: string;
  eleve_id: string;
  periode_id: string;
  classe_id: string;
  publie_le: Date | null;
  statut: string | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
  periode?: Periode;
  classe?: Classe;
  lignes?: BulletinLigne[];
}

export interface BulletinLigne {
  id: string;
  bulletin_id: string;
  matiere_id: string;
  moyenne: number | null;
  rang: number | null;
  commentaire_enseignant: string | null;
  created_at: Date;
  updated_at: Date;
  bulletin?: Bulletin;
  matiere?: Matiere;
}

/**
 * *
 *  * =========================
 *  * 6) TEMPS & PLANNING
 *  * =========================
 */
export interface CreneauHoraire {
  id: string;
  etablissement_id: string;
  nom: string;
  heure_debut: string;
  heure_fin: string;
  ordre: number | null;
  created_at: Date;
  updated_at: Date;
  emploiDuTemps?: EmploiDuTemps[];
  sessionsAppel?: SessionAppel[];
}

export interface EmploiDuTemps {
  id: string;
  classe_id: string;
  cours_id: string | null;
  matiere_id: string | null;
  enseignant_id: string | null;
  salle_id: string | null;
  jour_semaine: number;
  heure_debut: string;
  heure_fin: string;
  creneau_horaire_id: string | null;
  effectif_du: Date | null;
  effectif_au: Date | null;
  created_at: Date;
  updated_at: Date;
  classe?: Classe;
  cours?: Cours | null;
  matiere?: Matiere | null;
  enseignant?: Enseignant | null;
  salle?: Salle | null;
  creneau?: CreneauHoraire | null;
  sessionsAppel?: SessionAppel[];
}

export interface EvenementCalendrier {
  id: string;
  etablissement_id: string;
  site_id: string | null;
  titre: string;
  debut: Date;
  fin: Date;
  type: string | null;
  description: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  site?: Site | null;
}

/**
 * *
 *  * =========================
 *  * 7) PRÉSENCES
 *  * =========================
 */
export interface SessionAppel {
  id: string;
  classe_id: string;
  emploi_du_temps_id: string | null;
  date: Date;
  creneau_horaire_id: string;
  pris_par_enseignant_id: string | null;
  pris_le: Date | null;
  created_at: Date;
  updated_at: Date;
  classe?: Classe;
  emploi?: EmploiDuTemps | null;
  creneau?: CreneauHoraire;
  prisPar?: Enseignant | null;
  presences?: PresenceEleve[];
}

export interface PresenceEleve {
  id: string;
  session_appel_id: string;
  eleve_id: string;
  statut: StatutPresence;
  minutes_retard: number | null;
  note: string | null;
  created_at: Date;
  updated_at: Date;
  session?: SessionAppel;
  eleve?: Eleve;
}

export interface MotifAbsence {
  id: string;
  etablissement_id: string;
  nom: string;
  est_excuse_par_defaut: boolean;
  created_at: Date;
  updated_at: Date;
  justificatifs?: JustificatifAbsence[];
}

export interface JustificatifAbsence {
  id: string;
  eleve_id: string;
  date_debut: Date;
  date_fin: Date;
  motif_absence_id: string | null;
  document_url: string | null;
  approuve_par: string | null;
  approuve_le: Date | null;
  statut: string | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
  motif?: MotifAbsence | null;
}

export interface PresencePersonnel {
  id: string;
  personnel_id: string;
  date: Date | null;
  statut: string | null;
  note: string | null;
  created_at: Date;
  updated_at: Date;
  personnel?: Personnel;
}

/**
 * *
 *  * =========================
 *  * 8) DISCIPLINE
 *  * =========================
 */
export interface IncidentDisciplinaire {
  id: string;
  eleve_id: string;
  date: Date;
  signale_par: string | null;
  description: string;
  gravite: number | null;
  statut: string | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
  sanctions?: SanctionDisciplinaire[];
}

export interface SanctionDisciplinaire {
  id: string;
  incident_id: string;
  type_action: string;
  debut: Date | null;
  fin: Date | null;
  notes: string | null;
  decide_par: string | null;
  created_at: Date;
  updated_at: Date;
  incident?: IncidentDisciplinaire;
}

export interface Recompense {
  id: string;
  eleve_id: string;
  date: Date;
  points: number | null;
  raison: string | null;
  donne_par: string | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
}

/**
 * *
 *  * =========================
 *  * 9) COMMUNICATION
 *  * =========================
 */
export interface CanalCommunication {
  id: string;
  etablissement_id: string;
  type: TypeCanal;
  nom: string;
  config_json: JsonValue | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
}

export interface Annonce {
  id: string;
  etablissement_id: string;
  titre: string;
  contenu: string;
  publie_le: Date | null;
  cree_par: string | null;
  cible_json: JsonValue | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
}

export interface Message {
  id: string;
  etablissement_id: string;
  expediteur_utilisateur_id: string;
  objet: string | null;
  corps: string;
  envoye_le: Date | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  expediteur?: Utilisateur;
  destinataires?: MessageDestinataire[];
}

export interface MessageDestinataire {
  message_id: string;
  utilisateur_id: string;
  statut: string | null;
  lu_le: Date | null;
  message?: Message;
  utilisateur?: Utilisateur;
}

export interface Notification {
  id: string;
  utilisateur_id: string;
  type: string;
  payload_json: JsonValue | null;
  lu_le: Date | null;
  created_at: Date;
  updated_at: Date;
  utilisateur?: Utilisateur;
}

/**
 * *
 *  * =========================
 *  * 10) FINANCE
 *  * =========================
 */
export interface CatalogueFrais {
  id: string;
  etablissement_id: string;
  nom: string;
  description: string | null;
  montant: Decimal;
  devise: string;
  est_recurrent: boolean;
  periodicite: string | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  lignesFacture?: FactureLigne[];
}

export interface PlanPaiementEleve {
  id: string;
  eleve_id: string;
  annee_scolaire_id: string;
  plan_json: JsonValue;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
  annee?: AnneeScolaire;
}

export interface Facture {
  id: string;
  etablissement_id: string;
  eleve_id: string;
  annee_scolaire_id: string;
  numero_facture: string;
  date_emission: Date;
  date_echeance: Date | null;
  statut: StatutFacture;
  total_montant: Decimal;
  devise: string;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  eleve?: Eleve;
  annee?: AnneeScolaire;
  lignes?: FactureLigne[];
  paiements?: Paiement[];
}

export interface FactureLigne {
  id: string;
  facture_id: string;
  catalogue_frais_id: string | null;
  libelle: string;
  quantite: number;
  prix_unitaire: Decimal;
  montant: Decimal;
  created_at: Date;
  updated_at: Date;
  facture?: Facture;
  frais?: CatalogueFrais | null;
}

export interface Paiement {
  id: string;
  facture_id: string;
  paye_le: Date;
  montant: Decimal;
  methode: string | null;
  reference: string | null;
  recu_par: string | null;
  created_at: Date;
  updated_at: Date;
  facture?: Facture;
}

export interface Remise {
  id: string;
  etablissement_id: string;
  nom: string;
  type: string;
  valeur: number;
  regles_json: JsonValue | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
}

/**
 * *
 *  * =========================
 *  * 11) BIBLIOTHÈQUE
 *  * =========================
 */
export interface RessourceBibliotheque {
  id: string;
  etablissement_id: string;
  type: string;
  titre: string;
  code: string | null;
  auteur: string | null;
  editeur: string | null;
  annee: number | null;
  stock: number | null;
  created_at: Date;
  updated_at: Date;
  emprunts?: Emprunt[];
}

export interface Emprunt {
  id: string;
  ressource_bibliotheque_id: string;
  eleve_id: string | null;
  personnel_id: string | null;
  emprunte_le: Date;
  du_le: Date | null;
  retourne_le: Date | null;
  statut: string | null;
  created_at: Date;
  updated_at: Date;
  ressource?: RessourceBibliotheque;
  eleve?: Eleve | null;
  personnel?: Personnel | null;
}

/**
 * *
 *  * =========================
 *  * 12) TRANSPORT / CANTINE
 *  * =========================
 */
export interface LigneTransport {
  id: string;
  etablissement_id: string;
  nom: string;
  infos_vehicule_json: JsonValue | null;
  created_at: Date;
  updated_at: Date;
  arrets?: ArretTransport[];
  abonnements?: AbonnementTransport[];
}

export interface ArretTransport {
  id: string;
  ligne_transport_id: string;
  nom: string;
  geo_json: JsonValue | null;
  ordre: number | null;
  created_at: Date;
  updated_at: Date;
  ligne?: LigneTransport;
  AbonnementTransport?: AbonnementTransport[];
}

export interface AbonnementTransport {
  id: string;
  eleve_id: string;
  annee_scolaire_id: string;
  ligne_transport_id: string;
  arret_transport_id: string | null;
  statut: string | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
  annee?: AnneeScolaire;
  ligne?: LigneTransport;
  arret?: ArretTransport | null;
}

export interface FormuleCantine {
  id: string;
  etablissement_id: string;
  nom: string;
  prix: Decimal;
  periodicite: string | null;
  created_at: Date;
  updated_at: Date;
  abonnements?: AbonnementCantine[];
}

export interface AbonnementCantine {
  id: string;
  eleve_id: string;
  annee_scolaire_id: string;
  formule_cantine_id: string;
  statut: string | null;
  created_at: Date;
  updated_at: Date;
  eleve?: Eleve;
  annee?: AnneeScolaire;
  formule?: FormuleCantine;
}

/**
 * *
 *  * =========================
 *  * 13) DOCUMENTS
 *  * =========================
 */
export interface Fichier {
  id: string;
  etablissement_id: string;
  proprietaire_utilisateur_id: string | null;
  fournisseur_stockage: string | null;
  chemin: string;
  type_mime: string | null;
  taille: number | null;
  checksum: string | null;
  televerse_le: Date;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  proprietaire?: Utilisateur | null;
  liens?: LienFichier[];
}

export interface LienFichier {
  id: string;
  fichier_id: string;
  type_entite: string;
  id_entite: string;
  tag: string | null;
  created_at: Date;
  updated_at: Date;
  fichier?: Fichier;
}

/**
 * *
 *  * =========================
 *  * 14) AUDIT & INTÉGRATIONS
 *  * =========================
 */
export interface JournalAudit {
  id: string;
  etablissement_id: string;
  acteur_utilisateur_id: string | null;
  action: string;
  type_entite: string | null;
  id_entite: string | null;
  avant_json: JsonValue | null;
  apres_json: JsonValue | null;
  ip: string | null;
  date_action: Date;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
  acteur?: Utilisateur | null;
}

export interface Webhook {
  id: string;
  etablissement_id: string;
  url: string;
  evenements_json: JsonValue | null;
  secret: string | null;
  est_actif: boolean;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
}

export interface JetonIntegration {
  id: string;
  etablissement_id: string;
  fournisseur: string;
  token_json: JsonValue;
  expire_le: Date | null;
  created_at: Date;
  updated_at: Date;
  etablissement?: Etablissement;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;

type Decimal = { valueOf(): string };
