import type { Etablissement, Profil, Utilisateur } from "../generated/zod";

export type menu = {
  key: string;
  name: string;
  path?: string;
  icon?: React.ReactNode;
  elements?: React.ReactNode;
  submodules?: menu[];
};

export type AppRoute = {
  path: string;
  element: React.ReactNode;
};

export type roles = 'ADMIN' | 'DIRECTION' | 'SECRETARIAT' | 'ENSEIGNANT' | 'COMPTABLE' | 'SURVEILLANT' | 'PARENT' | 'ELEVE';

export type componentId =
  // ============ADMIN ============

  'ADM.PROFILE.SELECT.ETABLISSEMENT'
  | 'ADM.BARRE.SELECT.ETABLISSEMENT'

  // ========= SECTION ETABLISSEMENT =========
  ////profile etablissement
  | 'ET.PROFILE.MENUACTION'
  | 'ET.PROFILE.MENUACTION.LIST'
  | 'ET.PROFILE.MENUACTION.PARAMETRE'
  | 'ET.PROFILE.MENUACTION.ADD'
  | 'ET.PROFILE.MENUACTION.DASHBOARD'
  //// sites
  | 'ET.SITES.MENUACTION'
  | 'ET.SITES.MENUACTION.LIST'
  | 'ET.SITES.MENUACTION.PARAMETRE'
  | 'ET.SITES.MENUACTION.ADD'
  | 'ET.SITES.MENUACTION.DASHBOARD'
  //// salles
  | 'ET.SALLES.MENUACTION'
  | 'ET.SALLES.MENUACTION.LIST'
  | 'ET.SALLES.MENUACTION.PARAMETRE'
  | 'ET.SALLES.MENUACTION.ADD'
  | 'ET.SALLES.MENUACTION.DASHBOARD'
  //// annees scolaires
  | 'ET.ANNEESCOLAIRES.MENUACTION'
  | 'ET.ANNEESCOLAIRES.MENUACTION.LIST'
  | 'ET.ANNEESCOLAIRES.MENUACTION.PARAMETRE'
  | 'ET.ANNEESCOLAIRES.MENUACTION.ADD'
  | 'ET.ANNEESCOLAIRES.MENUACTION.DASHBOARD'
  //// Période
  | 'ET.PERIODES.MENUACTION'
  | 'ET.PERIODES.MENUACTION.LIST'
  | 'ET.PERIODES.MENUACTION.PARAMETRE'
  | 'ET.PERIODES.MENUACTION.ADD'
  | 'ET.PERIODES.MENUACTION.DASHBOARD'
  //// referentiels
  | 'ET.REFERENTIELS.MENUACTION'
  | 'ET.REFERENTIELS.MENUACTION.LIST'
  | 'ET.REFERENTIELS.MENUACTION.PARAMETRE'
  | 'ET.REFERENTIELS.MENUACTION.ADD'
  | 'ET.REFERENTIELS.MENUACTION.DASHBOARD'
  
  // ========= SECTION COMPTE ET SECURITE =========
  //// utilisateurs
  | 'CS.UTILISATEURS.MENUACTION'
  | 'CS.UTILISATEURS.MENUACTION.LIST'
  | 'CS.UTILISATEURS.MENUACTION.PARAMETRE'
  | 'CS.UTILISATEURS.MENUACTION.ADD'
  | 'CS.UTILISATEURS.MENUACTION.DASHBOARD'
  | 'CS.UTILISATEURS.MENUACTION.APPROV.LIST'
  //// roles
  | 'CS.ROLES.MENUACTION'
  | 'CS.ROLES.MENUACTION.LIST'
  | 'CS.ROLES.MENUACTION.PARAMETRE'
  | 'CS.ROLES.MENUACTION.ADD'
  | 'CS.ROLES.MENUACTION.DASHBOARD'
  //// profils
  | 'CS.PROFILS.MENUACTION'
  | 'CS.PROFILS.MENUACTION.LIST'
  | 'CS.PROFILS.MENUACTION.PARAMETRE'
  | 'CS.PROFILS.MENUACTION.ADD'
  | 'CS.PROFILS.MENUACTION.DASHBOARD'
  //// permissions
  | 'CS.PERMISSIONS.MENUACTION'
  | 'CS.PERMISSIONS.MENUACTION.LIST'
  | 'CS.PERMISSIONS.MENUACTION.PARAMETRE'
  | 'CS.PERMISSIONS.MENUACTION.ADD'
  | 'CS.PERMISSIONS.MENUACTION.DASHBOARD'
  //// affectations & scope
  | 'CS.AFFECTATIONS.MENUACTION'
  | 'CS.AFFECTATIONS.MENUACTION.LIST'
  | 'CS.AFFECTATIONS.MENUACTION.PARAMETRE'
  | 'CS.AFFECTATIONS.MENUACTION.ADD'
  | 'CS.AFFECTATIONS.MENUACTION.DASHBOARD'

  // ========= SECTION Scolarite =========
  //// inscriptions
  | 'SC.INSCRIPTIONS.MENUACTION'
  | 'SC.INSCRIPTIONS.MENUACTION.LIST'
  | 'SC.INSCRIPTIONS.MENUACTION.PARAMETRE'
  | 'SC.INSCRIPTIONS.MENUACTION.ADD'
  | 'SC.INSCRIPTIONS.MENUACTION.DASHBOARD'

  //// classes
  | 'SC.CLASSES.MENUACTION'
  | 'SC.CLASSES.MENUACTION.LIST'
  | 'SC.CLASSES.MENUACTION.PARAMETRE'
  | 'SC.CLASSES.MENUACTION.ADD'
  | 'SC.CLASSES.MENUACTION.DASHBOARD'

  //// niveaux
  | 'SC.NIVEAUX.MENUACTION'
  | 'SC.NIVEAUX.MENUACTION.LIST'
  | 'SC.NIVEAUX.MENUACTION.PARAMETRE'
  | 'SC.NIVEAUX.MENUACTION.ADD'
  | 'SC.NIVEAUX.MENUACTION.DASHBOARD'

  //// parent/tuteur
  | 'SC.PARENTSTUTEURS.MENUACTION'
  | 'SC.PARENTSTUTEURS.MENUACTION.LIST'
  | 'SC.PARENTSTUTEURS.MENUACTION.PARAMETRE'
  | 'SC.PARENTSTUTEURS.MENUACTION.ADD'
  | 'SC.PARENTSTUTEURS.MENUACTION.DASHBOARD'

  //// identifiants
  | 'SC.IDENTIFIANTS.MENUACTION'
  | 'SC.IDENTIFIANTS.MENUACTION.LIST'
  | 'SC.IDENTIFIANTS.MENUACTION.PARAMETRE'
  | 'SC.IDENTIFIANTS.MENUACTION.ADD'
  | 'SC.IDENTIFIANTS.MENUACTION.DASHBOARD'

  //// eleves
  | 'SC.ELEVES.MENUACTION'
  | 'SC.ELEVES.MENUACTION.LIST'
  | 'SC.ELEVES.MENUACTION.PARAMETRE'
  | 'SC.ELEVES.MENUACTION.ADD'
  | 'SC.ELEVES.MENUACTION.DASHBOARD'
  // ========= SECTION PERSONNEL =========
  //// personnels
  | 'PE.PERSONNELS.MENUACTION'
  | 'PE.PERSONNELS.MENUACTION.LIST'
  | 'PE.PERSONNELS.MENUACTION.PARAMETRE'
  | 'PE.PERSONNELS.MENUACTION.ADD'
  | 'PE.PERSONNELS.MENUACTION.DASHBOARD'
  //// enseignants
  | 'PE.ENSEIGNANTS.MENUACTION'
  | 'PE.ENSEIGNANTS.MENUACTION.LIST'
  | 'PE.ENSEIGNANTS.MENUACTION.PARAMETRE'
  | 'PE.ENSEIGNANTS.MENUACTION.ADD'
  | 'PE.ENSEIGNANTS.MENUACTION.DASHBOARD'
  //// départements
  | 'PE.DEPARTEMENTS.MENUACTION'
  | 'PE.DEPARTEMENTS.MENUACTION.LIST'
  | 'PE.DEPARTEMENTS.MENUACTION.PARAMETRE'
  | 'PE.DEPARTEMENTS.MENUACTION.ADD'
  | 'PE.DEPARTEMENTS.MENUACTION.DASHBOARD'
  // ========= SECTION PEDAGOGIE =========
  //// matières
  | 'PD.MATIERES.MENUACTION'
  | 'PD.MATIERES.MENUACTION.LIST'
  | 'PD.MATIERES.MENUACTION.PARAMETRE'
  | 'PD.MATIERES.MENUACTION.ADD'
  | 'PD.MATIERES.MENUACTION.DASHBOARD'
  //// programmes
  | 'PD.PROGRAMMES.MENUACTION'
  | 'PD.PROGRAMMES.MENUACTION.LIST'
  | 'PD.PROGRAMMES.MENUACTION.PARAMETRE'
  | 'PD.PROGRAMMES.MENUACTION.ADD'
  | 'PD.PROGRAMMES.MENUACTION.DASHBOARD'
  //// cours
  | 'PD.COURS.MENUACTION'
  | 'PD.COURS.MENUACTION.LIST'
  | 'PD.COURS.MENUACTION.PARAMETRE'
  | 'PD.COURS.MENUACTION.ADD'
  | 'PD.COURS.MENUACTION.DASHBOARD'
  //// évaluations
  | 'PD.EVALUATIONS.MENUACTION'
  | 'PD.EVALUATIONS.MENUACTION.LIST'
  | 'PD.EVALUATIONS.MENUACTION.PARAMETRE'
  | 'PD.EVALUATIONS.MENUACTION.ADD'
  | 'PD.EVALUATIONS.MENUACTION.DASHBOARD'
  //// notes
  | 'PD.NOTES.MENUACTION'
  | 'PD.NOTES.MENUACTION.LIST'
  | 'PD.NOTES.MENUACTION.PARAMETRE'
  | 'PD.NOTES.MENUACTION.ADD'
  | 'PD.NOTES.MENUACTION.DASHBOARD'
  //// bulletins
  | 'PD.BULLETINS.MENUACTION'
  | 'PD.BULLETINS.MENUACTION.LIST'
  | 'PD.BULLETINS.MENUACTION.PARAMETRE'
  | 'PD.BULLETINS.MENUACTION.ADD'
  | 'PD.BULLETINS.MENUACTION.DASHBOARD'
  //// règles de notes
  | 'PD.REGLESNOTES.MENUACTION'
  | 'PD.REGLESNOTES.MENUACTION.LIST'
  | 'PD.REGLESNOTES.MENUACTION.PARAMETRE'
  | 'PD.REGLESNOTES.MENUACTION.ADD'
  | 'PD.REGLESNOTES.MENUACTION.DASHBOARD'
  // ========= SECTION EMPLOI DU TEMPS =========
  //// emploi du temps
  | 'EDT.EMPLOIDUTEMPS.MENUACTION'
  | 'EDT.EMPLOIDUTEMPS.MENUACTION.LIST'
  | 'EDT.EMPLOIDUTEMPS.MENUACTION.PARAMETRE'
  | 'EDT.EMPLOIDUTEMPS.MENUACTION.ADD'
  | 'EDT.EMPLOIDUTEMPS.MENUACTION.DASHBOARD'
  //// evenements
  | 'EDT.EVENEMENTS.MENUACTION'
  | 'EDT.EVENEMENTS.MENUACTION.LIST'
  | 'EDT.EVENEMENTS.MENUACTION.PARAMETRE'
  | 'EDT.EVENEMENTS.MENUACTION.ADD'
  | 'EDT.EVENEMENTS.MENUACTION.DASHBOARD'
  // ========= SECTION PRESENCES =========
  | 'PR.SESSIONSAPPEL.MENUACTION'
  | 'PR.SESSIONSAPPEL.MENUACTION.LIST'
  | 'PR.SESSIONSAPPEL.MENUACTION.PARAMETRE'
  | 'PR.SESSIONSAPPEL.MENUACTION.ADD'
  | 'PR.SESSIONSAPPEL.MENUACTION.DASHBOARD'
  | 'PR.PRESENCESELEVES.MENUACTION'
  | 'PR.PRESENCESELEVES.MENUACTION.LIST'
  | 'PR.PRESENCESELEVES.MENUACTION.PARAMETRE'
  | 'PR.PRESENCESELEVES.MENUACTION.ADD'
  | 'PR.PRESENCESELEVES.MENUACTION.DASHBOARD'
  | 'PR.JUSTIFICATIFS.MENUACTION'
  | 'PR.JUSTIFICATIFS.MENUACTION.LIST'
  | 'PR.JUSTIFICATIFS.MENUACTION.PARAMETRE'
  | 'PR.JUSTIFICATIFS.MENUACTION.ADD'
  | 'PR.JUSTIFICATIFS.MENUACTION.DASHBOARD'
  | 'PR.PRESENCESPERSONNEL.MENUACTION'
  | 'PR.PRESENCESPERSONNEL.MENUACTION.LIST'
  | 'PR.PRESENCESPERSONNEL.MENUACTION.PARAMETRE'
  | 'PR.PRESENCESPERSONNEL.MENUACTION.ADD'
  | 'PR.PRESENCESPERSONNEL.MENUACTION.DASHBOARD'
;



export type AproveUserDataType = {
  etablissement: Pick<Etablissement, "nom">;
  utilisateur: Pick<Utilisateur, "email" | "telephone" | "mot_de_passe_hash">;
  profil: Pick<Profil, "prenom" | "nom" | "date_naissance" | "genre" | "adresse">;
}

export type WizardDataUserPersonnel = {
  etablissement?: {
    id: string;
  };
  utilisateur?: Partial<Utilisateur>;
  profil?: Partial<Profil>;
  role_id?: string | null;
  etablissement_id?: string | null;
};



