import type { Etablissement, Profil, Utilisateur } from "../generated/zod";

export type menu = {
  key: string;
  name: string;
  path?: string;
  icon?: React.ReactNode;
  elements?: React.ReactNode;
  submodules?: menu[];
};

export type AppRoute = {
  path: string;
  element: React.ReactNode;
};

export type roles = 'ADMIN' | 'DIRECTION' | 'SECRETARIAT' | 'ENSEIGNANT' | 'COMPTABLE' | 'SURVEILLANT' | 'PARENT' | 'ELEVE';

export type componentId =
  // ============ADMIN ============

  'ADM.PROFILE.SELECT.ETABLISSEMENT'
  | 'ADM.BARRE.SELECT.ETABLISSEMENT'

  // ========= SECTION ETABLISSEMENT =========
  ////profile etablissement
  | 'ET.PROFILE.MENUACTION'
  | 'ET.PROFILE.MENUACTION.LIST'
  | 'ET.PROFILE.MENUACTION.PARAMETRE'
  | 'ET.PROFILE.MENUACTION.ADD'
  | 'ET.PROFILE.MENUACTION.DASHBOARD'
  //// sites
  | 'ET.SITES.MENUACTION'
  | 'ET.SITES.MENUACTION.LIST'
  | 'ET.SITES.MENUACTION.PARAMETRE'
  | 'ET.SITES.MENUACTION.ADD'
  | 'ET.SITES.MENUACTION.DASHBOARD'
  //// salles
  | 'ET.SALLES.MENUACTION'
  | 'ET.SALLES.MENUACTION.LIST'
  | 'ET.SALLES.MENUACTION.PARAMETRE'
  | 'ET.SALLES.MENUACTION.ADD'
  | 'ET.SALLES.MENUACTION.DASHBOARD'
  //// annees scolaires
  | 'ET.ANNEESCOLAIRES.MENUACTION'
  | 'ET.ANNEESCOLAIRES.MENUACTION.LIST'
  | 'ET.ANNEESCOLAIRES.MENUACTION.PARAMETRE'
  | 'ET.ANNEESCOLAIRES.MENUACTION.ADD'
  | 'ET.ANNEESCOLAIRES.MENUACTION.DASHBOARD'
  //// Période
  | 'ET.PERIODES.MENUACTION'
  | 'ET.PERIODES.MENUACTION.LIST'
  | 'ET.PERIODES.MENUACTION.PARAMETRE'
  | 'ET.PERIODES.MENUACTION.ADD'
  | 'ET.PERIODES.MENUACTION.DASHBOARD'
  
  // ========= SECTION COMPTE ET SECURITE =========
  //// utilisateurs
  | 'CS.UTILISATEURS.MENUACTION'
  | 'CS.UTILISATEURS.MENUACTION.LIST'
  | 'CS.UTILISATEURS.MENUACTION.PARAMETRE'
  | 'CS.UTILISATEURS.MENUACTION.ADD'
  | 'CS.UTILISATEURS.MENUACTION.DASHBOARD'
  | 'CS.UTILISATEURS.MENUACTION.APPROV.LIST'
  //// roles
  | 'CS.ROLES.MENUACTION'
  | 'CS.ROLES.MENUACTION.LIST'
  | 'CS.ROLES.MENUACTION.PARAMETRE'
  | 'CS.ROLES.MENUACTION.ADD'
  | 'CS.ROLES.MENUACTION.DASHBOARD'
  //// profils
  | 'CS.PROFILS.MENUACTION'
  | 'CS.PROFILS.MENUACTION.LIST'
  | 'CS.PROFILS.MENUACTION.PARAMETRE'
  | 'CS.PROFILS.MENUACTION.ADD'
  | 'CS.PROFILS.MENUACTION.DASHBOARD'
  //// permissions
  | 'CS.PERMISSIONS.MENUACTION'
  | 'CS.PERMISSIONS.MENUACTION.LIST'
  | 'CS.PERMISSIONS.MENUACTION.PARAMETRE'
  | 'CS.PERMISSIONS.MENUACTION.ADD'
  | 'CS.PERMISSIONS.MENUACTION.DASHBOARD'

  // ========= SECTION Scolarite =========
  //// inscriptions
  | 'SC.INSCRIPTIONS.MENUACTION'
  | 'SC.INSCRIPTIONS.MENUACTION.LIST'
  | 'SC.INSCRIPTIONS.MENUACTION.PARAMETRE'
  | 'SC.INSCRIPTIONS.MENUACTION.ADD'
  | 'SC.INSCRIPTIONS.MENUACTION.DASHBOARD'

  //// classes
  | 'SC.CLASSES.MENUACTION'
  | 'SC.CLASSES.MENUACTION.LIST'
  | 'SC.CLASSES.MENUACTION.PARAMETRE'
  | 'SC.CLASSES.MENUACTION.ADD'
  | 'SC.CLASSES.MENUACTION.DASHBOARD'

  //// niveaux
  | 'SC.NIVEAUX.MENUACTION'
  | 'SC.NIVEAUX.MENUACTION.LIST'
  | 'SC.NIVEAUX.MENUACTION.PARAMETRE'
  | 'SC.NIVEAUX.MENUACTION.ADD'
  | 'SC.NIVEAUX.MENUACTION.DASHBOARD'

  //// parent/tuteur
  | 'SC.PARENTSTUTEURS.MENUACTION'
  | 'SC.PARENTSTUTEURS.MENUACTION.LIST'
  | 'SC.PARENTSTUTEURS.MENUACTION.PARAMETRE'
  | 'SC.PARENTSTUTEURS.MENUACTION.ADD'
  | 'SC.PARENTSTUTEURS.MENUACTION.DASHBOARD'

  //// identifiants
  | 'SC.IDENTIFIANTS.MENUACTION'
  | 'SC.IDENTIFIANTS.MENUACTION.LIST'
  | 'SC.IDENTIFIANTS.MENUACTION.PARAMETRE'
  | 'SC.IDENTIFIANTS.MENUACTION.ADD'
  | 'SC.IDENTIFIANTS.MENUACTION.DASHBOARD'

  //// eleves
  | 'SC.ELEVES.MENUACTION'
  | 'SC.ELEVES.MENUACTION.LIST'
  | 'SC.ELEVES.MENUACTION.PARAMETRE'
  | 'SC.ELEVES.MENUACTION.ADD'
  | 'SC.ELEVES.MENUACTION.DASHBOARD'
  



export type AproveUserDataType = {
  etablissement: Pick<Etablissement, "nom">;
  utilisateur: Pick<Utilisateur, "email" | "telephone" | "mot_de_passe_hash">;
  profil: Pick<Profil, "prenom" | "nom" | "date_naissance" | "genre" | "adresse">;
}

export type WizardDataUserPersonnel = {
  etablissement?: {
    id: string;
  };
  utilisateur?: Partial<Utilisateur>;
  profil?: Partial<Profil>;
  role_id?: string | null;
  etablissement_id?: string | null;
};