import { Application, Router } from "express";
import UserApp from "../modules/user/application/user.app";
import EtablissementApp from "../modules/etablissement/application/etablissement.app";
import RolesApp from "../modules/roles/application/roles.app";
import RoleUserApp from "../modules/roles_user/application/roles_user.app";
import SiteApp from "../modules/site/application/site.app";
import ProfileApp from "../modules/profile/application/profile.app";
import PermissionApp from "../modules/permission/application/permission.app";
import AuthApp from "../modules/auth/application/auth.app";
import { tenantMiddleware } from "../../middleware/tenant";
import SalleApp from "../modules/salle/application/salle.app";
import AnneeScolaireApp from "../modules/annee_scolaire/application/anneeScolaire.app";
import InitialisationEtablissementApp from "../modules/initialisation_etablissement/application/initialisation_etablissement.app";
import PeriodeApp from "../modules/periode/application/periode.app";
import ReferencielApp from "../modules/referenciel/application/referenciel.app";
import InscriptionApp from "../modules/inscription/application/inscription.app";
import ClasseApp from "../modules/classe/application/classe.app";
import NiveauApp from "../modules/niveau/application/niveau.app";
import ParentTuteurApp from "../modules/parent_tuteur/application/parent_tuteur.app";
import IdentifiantEleveApp from "../modules/identifiant_eleve/application/identifiant_eleve.app";
import EleveApp from "../modules/eleve/application/eleve.app";
import PersonnelApp from "../modules/personnel/application/personnel.app";
import EnseignantApp from "../modules/enseignant/application/enseignant.app";
import DepartementApp from "../modules/departement/application/departement.app";
import MatiereApp from "../modules/matiere/application/matiere.app";
import ProgrammeApp from "../modules/programme/application/programme.app";
import CoursApp from "../modules/cours/application/cours.app";
import EvaluationApp from "../modules/evaluation/application/evaluation.app";
import NoteApp from "../modules/note/application/note.app";
import BulletinApp from "../modules/bulletin/application/bulletin.app";
import RegleNoteApp from "../modules/regle_note/application/regle_note.app";
import EmploiDuTempsApp from "../modules/emploi_du_temps/application/emploi_du_temps.app";
import EvenementCalendrierApp from "../modules/evenement_calendrier/application/evenement_calendrier.app";
import CreneauHoraireApp from "../modules/creneau_horaire/application/creneau_horaire.app";
import LigneTransportApp from "../modules/ligne_transport/application/ligne_transport.app";
import ArretTransportApp from "../modules/arret_transport/application/arret_transport.app";
import FormuleCantineApp from "../modules/formule_cantine/application/formule_cantine.app";
import AbonnementTransportApp from "../modules/abonnement_transport/application/abonnement_transport.app";
import AbonnementCantineApp from "../modules/abonnement_cantine/application/abonnement_cantine.app";
import SessionAppelApp from "../modules/session_appel/application/session_appel.app";
import PresenceEleveApp from "../modules/presence_eleve/application/presence_eleve.app";
import MotifAbsenceApp from "../modules/motif_absence/application/motif_absence.app";
import JustificatifAbsenceApp from "../modules/justificatif_absence/application/justificatif_absence.app";
import PresencePersonnelApp from "../modules/presence_personnel/application/presence_personnel.app";
import IncidentDisciplinaireApp from "../modules/incident_disciplinaire/application/incident_disciplinaire.app";
import SanctionDisciplinaireApp from "../modules/sanction_disciplinaire/application/sanction_disciplinaire.app";
import RecompenseApp from "../modules/recompense/application/recompense.app";
import CatalogueFraisApp from "../modules/catalogue_frais/application/catalogue_frais.app";
import RemiseApp from "../modules/remise/application/remise.app";
import FactureApp from "../modules/facture/application/facture.app";
import PaiementApp from "../modules/paiement/application/paiement.app";
import PlanPaiementEleveApp from "../modules/plan_paiement_eleve/application/plan_paiement_eleve.app";
import FinanceRelanceApp from "../modules/finance_relance/application/finance_relance.app";
import FacturationRecurrenteApp from "../modules/facturation_recurrente/application/facturation_recurrente.app";
import OperationFinanciereApp from "../modules/operation_financiere/application/operation_financiere.app";
import FinanceRecouvrementApp from "../modules/finance_recouvrement/application/finance_recouvrement.app";
import RessourceBibliothequeApp from "../modules/ressource_bibliotheque/application/ressource_bibliotheque.app";
import EmpruntApp from "../modules/emprunt/application/emprunt.app";

export class ApiRoutes {
  public app: Application;
  private router: Router;

  private user: UserApp;
  private auth: AuthApp;
  private roles: RolesApp;
  private rolesUser: RoleUserApp;
  private profile: ProfileApp;
  private permission: PermissionApp;

  private etablissement: EtablissementApp;
  private site: SiteApp;
  private salle: SalleApp;
  private anneeScolaire: AnneeScolaireApp;
  private initialisationEtablissement: InitialisationEtablissementApp;
  private periode: PeriodeApp;
  private referenciel: ReferencielApp;

  private inscription: InscriptionApp;
  private classe: ClasseApp;
  private niveau: NiveauApp;
  private parentTuteur: ParentTuteurApp;
  private identifiantEleve: IdentifiantEleveApp;
  private eleve: EleveApp;
  private personnel: PersonnelApp;
  private enseignant: EnseignantApp;
  private departement: DepartementApp;

  private matiere: MatiereApp;
  private programme: ProgrammeApp;
  private cours: CoursApp;
  private evaluation: EvaluationApp;
  private note: NoteApp;
  private bulletin: BulletinApp;
  private regleNote: RegleNoteApp;
  private emploiDuTemps: EmploiDuTempsApp;
  private evenementCalendrier: EvenementCalendrierApp;
  private creneauHoraire: CreneauHoraireApp;
  private ligneTransport: LigneTransportApp;
  private arretTransport: ArretTransportApp;
  private formuleCantine: FormuleCantineApp;
  private abonnementTransport: AbonnementTransportApp;
  private abonnementCantine: AbonnementCantineApp;

  private sessionAppel: SessionAppelApp;
  private presenceEleve: PresenceEleveApp;
  private motifAbsence: MotifAbsenceApp;
  private justificatifAbsence: JustificatifAbsenceApp;
  private presencePersonnel: PresencePersonnelApp;
  private incidentDisciplinaire: IncidentDisciplinaireApp;
  private sanctionDisciplinaire: SanctionDisciplinaireApp;
  private recompense: RecompenseApp;
  private catalogueFrais: CatalogueFraisApp;
  private remise: RemiseApp;
  private factureFinance: FactureApp;
  private paiementFinance: PaiementApp;
  private planPaiementFinance: PlanPaiementEleveApp;
  private financeRelance: FinanceRelanceApp;
  private facturationRecurrente: FacturationRecurrenteApp;
  private operationFinanciere: OperationFinanciereApp;
  private financeRecouvrement: FinanceRecouvrementApp;
  private ressourceBibliotheque: RessourceBibliothequeApp;
  private empruntBibliotheque: EmpruntApp;

  constructor(app: Application) {
    this.app = app;
    this.router = Router();
    this.user = new UserApp(app);
    this.auth = new AuthApp(app);
    this.roles = new RolesApp(app);
    this.rolesUser = new RoleUserApp(app);
    this.profile = new ProfileApp(app);
    this.permission = new PermissionApp(app);
    this.etablissement = new EtablissementApp(app);
    this.site = new SiteApp(app);
    this.salle = new SalleApp(app);
    this.anneeScolaire = new AnneeScolaireApp(app);
    this.initialisationEtablissement = new InitialisationEtablissementApp(app);
    this.periode = new PeriodeApp(app);
    this.referenciel = new ReferencielApp(app);
    this.inscription = new InscriptionApp(app);
    this.classe = new ClasseApp(app);
    this.niveau = new NiveauApp(app);
    this.parentTuteur = new ParentTuteurApp(app);
    this.identifiantEleve = new IdentifiantEleveApp(app);
    this.eleve = new EleveApp(app);
    this.personnel = new PersonnelApp(app);
    this.enseignant = new EnseignantApp(app);
    this.departement = new DepartementApp(app);
    this.matiere = new MatiereApp(app);
    this.programme = new ProgrammeApp(app);
    this.cours = new CoursApp(app);
    this.evaluation = new EvaluationApp(app);
    this.note = new NoteApp(app);
    this.bulletin = new BulletinApp(app);
    this.regleNote = new RegleNoteApp(app);
    this.emploiDuTemps = new EmploiDuTempsApp(app);
    this.evenementCalendrier = new EvenementCalendrierApp(app);
    this.creneauHoraire = new CreneauHoraireApp(app);
    this.ligneTransport = new LigneTransportApp(app);
    this.arretTransport = new ArretTransportApp(app);
    this.formuleCantine = new FormuleCantineApp(app);
    this.abonnementTransport = new AbonnementTransportApp(app);
    this.abonnementCantine = new AbonnementCantineApp(app);
    this.sessionAppel = new SessionAppelApp(app);
    this.presenceEleve = new PresenceEleveApp(app);
    this.motifAbsence = new MotifAbsenceApp(app);
    this.justificatifAbsence = new JustificatifAbsenceApp(app);
    this.presencePersonnel = new PresencePersonnelApp(app);
    this.incidentDisciplinaire = new IncidentDisciplinaireApp(app);
    this.sanctionDisciplinaire = new SanctionDisciplinaireApp(app);
    this.recompense = new RecompenseApp(app);
    this.catalogueFrais = new CatalogueFraisApp(app);
    this.remise = new RemiseApp(app);
    this.factureFinance = new FactureApp(app);
    this.paiementFinance = new PaiementApp(app);
    this.planPaiementFinance = new PlanPaiementEleveApp(app);
    this.financeRelance = new FinanceRelanceApp(app);
    this.facturationRecurrente = new FacturationRecurrenteApp(app);
    this.operationFinanciere = new OperationFinanciereApp(app);
    this.financeRecouvrement = new FinanceRecouvrementApp(app);
    this.ressourceBibliotheque = new RessourceBibliothequeApp(app);
    this.empruntBibliotheque = new EmpruntApp(app);
    this.routes();
  }

  public routes(): Router {
    this.router.use(tenantMiddleware);

    this.router.use("/auth", this.auth.routes());
    this.router.use("/roles", this.roles.routes());
    this.router.use("/user", this.user.routes());
    this.router.use("/roles_user", this.rolesUser.routes());
    this.router.use("/profile", this.profile.routes());
    this.router.use("/permission", this.permission.routes());

    this.router.use("/etablissement", this.etablissement.routes());
    this.router.use("/site", this.site.routes());
    this.router.use("/salle", this.salle.routes());
    this.router.use("/annee-scolaire", this.anneeScolaire.routes());
    this.router.use(
      "/initialisation-etablissement",
      this.initialisationEtablissement.routes(),
    );
    this.router.use("/periode", this.periode.routes());
    this.router.use("/referenciel", this.referenciel.routes());

    this.router.use("/inscription", this.inscription.routes());
    this.router.use("/classe", this.classe.routes());
    this.router.use("/niveau-scolaire", this.niveau.routes());
    this.router.use("/parent-tuteur", this.parentTuteur.routes());
    this.router.use("/identifiantEleve", this.identifiantEleve.routes());
    this.router.use("/eleve", this.eleve.routes());

    this.router.use("/personnel", this.personnel.routes());
    this.router.use("/enseignant", this.enseignant.routes());
    this.router.use("/departement", this.departement.routes());

    this.router.use("/matiere", this.matiere.routes());
    this.router.use("/programme", this.programme.routes());
    this.router.use("/cours", this.cours.routes());
    this.router.use("/evaluation", this.evaluation.routes());
    this.router.use("/note", this.note.routes());
    this.router.use("/bulletin", this.bulletin.routes());
    this.router.use("/regle-note", this.regleNote.routes());
    this.router.use("/emploi-du-temps", this.emploiDuTemps.routes());
    this.router.use("/evenement-calendrier", this.evenementCalendrier.routes());
    this.router.use("/creneau-horaire", this.creneauHoraire.routes());
    this.router.use("/ligne-transport", this.ligneTransport.routes());
    this.router.use("/arret-transport", this.arretTransport.routes());
    this.router.use("/formule-cantine", this.formuleCantine.routes());
    this.router.use("/abonnement-transport", this.abonnementTransport.routes());
    this.router.use("/abonnement-cantine", this.abonnementCantine.routes());

    this.router.use("/session-appel", this.sessionAppel.routes());
    this.router.use("/presence-eleve", this.presenceEleve.routes());
    this.router.use("/motif-absence", this.motifAbsence.routes());
    this.router.use("/justificatif-absence", this.justificatifAbsence.routes());
    this.router.use("/presence-personnel", this.presencePersonnel.routes());
    this.router.use("/incident-disciplinaire", this.incidentDisciplinaire.routes());
    this.router.use("/sanction-disciplinaire", this.sanctionDisciplinaire.routes());
    this.router.use("/recompense", this.recompense.routes());
    this.router.use("/catalogue-frais", this.catalogueFrais.routes());
    this.router.use("/remise", this.remise.routes());
    this.router.use("/facture", this.factureFinance.routes());
    this.router.use("/paiement", this.paiementFinance.routes());
    this.router.use("/plan-paiement-eleve", this.planPaiementFinance.routes());
    this.router.use("/finance-relance", this.financeRelance.routes());
    this.router.use("/facturation-recurrente", this.facturationRecurrente.routes());
    this.router.use("/operation-financiere", this.operationFinanciere.routes());
    this.router.use("/finance-recouvrement", this.financeRecouvrement.routes());
    this.router.use("/ressource-bibliotheque", this.ressourceBibliotheque.routes());
    this.router.use("/emprunt", this.empruntBibliotheque.routes());

    return this.router;
  }
}
