import { useEffect, useMemo, useState } from "react";
import { FiCheckCircle, FiClock, FiSettings, FiUsers } from "react-icons/fi";
import { useAuth } from "../../../../../hooks/useAuth";
import PresenceEleveService, { getPresenceStatusMeta, type PresenceEleveWithRelations } from "../../../../../services/presenceEleve.service";

type Props = { mode?: "overview" | "settings" };
function getErrorMessage(error: unknown) { if (typeof error === "object" && error !== null && "response" in error && typeof error.response === "object" && error.response !== null && "data" in error.response && typeof error.response.data === "object" && error.response.data !== null && "message" in error.response.data && typeof error.response.data.message === "string") return error.response.data.message; return "Impossible de charger les presences eleves."; }
export default function PresenceEleveOverview({ mode = "overview" }: Props) {
  const { etablissement_id } = useAuth();
  const [rows, setRows] = useState<PresenceEleveWithRelations[]>([]);
  const [errorMessage, setErrorMessage] = useState("");
  useEffect(() => { let active = true; const load = async () => { if (!etablissement_id) return; try { const service = new PresenceEleveService(); const result = await service.getForEtablissement(etablissement_id, { page: 1, take: 500, includeSpec: JSON.stringify({ session: { include: { classe: { include: { niveau: true, site: true, annee: true } }, creneau: true } }, eleve: { include: { utilisateur: { include: { profil: true } } } } }) }); if (!active) return; setRows(result?.status.success ? (result.data.data as PresenceEleveWithRelations[]) ?? [] : []); } catch (error) { if (!active) return; setErrorMessage(getErrorMessage(error)); } }; void load(); return () => { active = false; }; }, [etablissement_id]);
  const absents = useMemo(() => rows.filter((row) => row.statut === "ABSENT").length, [rows]);
  const retards = useMemo(() => rows.filter((row) => row.statut === "RETARD").length, [rows]);
  const excuses = useMemo(() => rows.filter((row) => row.statut === "EXCUSE").length, [rows]);
  return <div className="space-y-6">{errorMessage ? <div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{errorMessage}</div> : null}<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><FiUsers className="text-slate-500" /><p className="mt-2 text-3xl font-semibold text-slate-900">{rows.length}</p><p className="text-sm text-slate-500">Lignes</p></div><div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><FiCheckCircle className="text-slate-500" /><p className="mt-2 text-3xl font-semibold text-slate-900">{rows.filter((row) => row.statut === "PRESENT").length}</p><p className="text-sm text-slate-500">Presents</p></div><div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><FiClock className="text-slate-500" /><p className="mt-2 text-3xl font-semibold text-slate-900">{retards}</p><p className="text-sm text-slate-500">Retards</p></div><div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><FiSettings className="text-slate-500" /><p className="mt-2 text-3xl font-semibold text-slate-900">{absents + excuses}</p><p className="text-sm text-slate-500">Absences suivies</p></div></section>{mode === "overview" ? <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><div className="space-y-3">{rows.slice(0, 6).map((row) => { const meta = getPresenceStatusMeta(row.statut); return <div key={row.id} className="rounded-[22px] border border-slate-200 bg-slate-50 px-4 py-4"><p className="text-sm font-semibold text-slate-900">{row.eleve?.utilisateur?.profil?.prenom} {row.eleve?.utilisateur?.profil?.nom}</p><div className="mt-2 inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${meta.tone}">{meta.label}</div></div>; })}</div></section> : null}</div>;
}

