CREATE TABLE `facturations_recurrentes` (
  `id` VARCHAR(191) NOT NULL,
  `run_id` VARCHAR(191) NOT NULL,
  `etablissement_id` VARCHAR(191) NOT NULL,
  `catalogue_frais_id` VARCHAR(191) NOT NULL,
  `eleve_id` VARCHAR(191) NOT NULL,
  `annee_scolaire_id` VARCHAR(191) NOT NULL,
  `facture_id` VARCHAR(191) NOT NULL,
  `created_by_utilisateur_id` VARCHAR(191) NULL,
  `periodicite` VARCHAR(191) NOT NULL,
  `cycle_key` VARCHAR(191) NOT NULL,
  `cycle_label` VARCHAR(191) NOT NULL,
  `date_reference` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_factrec_cat_eleve_cycle` (`catalogue_frais_id`, `eleve_id`, `annee_scolaire_id`, `cycle_key`),
  KEY `idx_factrec_etab_date` (`etablissement_id`, `date_reference`),
  KEY `idx_factrec_catalogue_cycle` (`catalogue_frais_id`, `cycle_key`),
  KEY `idx_factrec_eleve_annee` (`eleve_id`, `annee_scolaire_id`),
  KEY `idx_factrec_run` (`run_id`),
  CONSTRAINT `fk_factrec_etab` FOREIGN KEY (`etablissement_id`) REFERENCES `etablissements`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_factrec_catalogue` FOREIGN KEY (`catalogue_frais_id`) REFERENCES `catalogue_frais`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_factrec_eleve` FOREIGN KEY (`eleve_id`) REFERENCES `eleves`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_factrec_annee` FOREIGN KEY (`annee_scolaire_id`) REFERENCES `annees_scolaires`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_factrec_facture` FOREIGN KEY (`facture_id`) REFERENCES `factures`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_factrec_createur` FOREIGN KEY (`created_by_utilisateur_id`) REFERENCES `utilisateurs`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
